permissions:
  pages: write
  contents: read
  id-token: write
  deployments: write

name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install modules
      run: npm install

    - name: Run tests
      id: tests
      run: npm run test
    
    - name: create html
      run: |
        mkdir dist
        echo 'Hello world' > dist/index.html

    - name: Archive build output
      run: tar --dereference --hard-dereference --directory dist/ -cvf artifact.tar .

    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: github-pages
        path: ./artifact.tar
        if-no-files-found: warn

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.0.4
