name: Classic Deploy

permissions:
  contents: read|write

on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Create html
      run: |
        mkdir dist
        echo 'Hello world' > dist/index.html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build
