name: Release Draft

on:
  release:

jobs:
  bar:
    runs-on: ["ubuntu-latest"]
    steps:
      - run: echo "event name is:" ${{ github.event_name }} 
      - run: echo "event type is:" ${{ github.event.action }} 
      - run: echo "event data is:" ${{ toJSON(github.event) }} 
