name: Format

on:
  issue_comment:
    types:
      - created

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
        - run: npm ci
        - run: npx prettier
        - run: echo "${{ github.event }}"
      - name: push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          commit: 'Code Format'
