name: Manual Tests Trigger

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  build:
    if: ${{ github.event.comment.body == '/test' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v3
      id: get-pr
      with:
        script: |
          /*
          const request = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          }
          core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
          try {
            const result = await github.pulls.get(request)
            return result.data
          } catch (err) {
            core.setFailed(`Request failed with error ${err}`)
          }
          */
          return 'trigger2'
    - uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ github.event.comment.id }}
        issue-number: ${{ github.event.issue.number }}
        edit-mode: replace
        token: ${{ secrets.GITHUB_TOKEN }}
        body: "\n\n 🔄 Start building chormatic..."
    - uses: actions/checkout@v2
      with:
        ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }}
    - name: Install modules
      run: npm install
    - name: Run tests
      id: tests
      run: npm run test
    - uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ github.event.comment.id }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: "\n\n ✅ Build done. Hosted on: ${{github.event.comment.id}}\n\n```bash\n${{env.MY_STRING}}\n```\n"
        reactions: 'rocket'
        edit-mode: replace