name: Trigger

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  job01:
    #  if: contains(github.event.comment.body, '/deploy')    # check if the comments come from pull request, exclude those from issue.
    runs-on: [ubuntu-latest]
    steps:
    - name: print body
      env:
        BODY: ${{ github.event.comment.body }}
      run: echo "Body - $BODY"
